contact/urls.py
# type:ignore
from django.urls import path

from contact import views

app_name = 'contact'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),

    # contact (CRUD)
    path('contact/<int:contact_id>/', views.contact, name='contact'),
    path('contact/create/', views.create, name='create'),
    path('contact/<int:contact_id>/update/', views.update, name='update'),
    path('contact/<int:contact_id>/delete/', views.delete, name='delete'),

    # user
    path('user/create/', views.register, name='register'),
    path('user/login/', views.login_view, name='login'),
    path('user/logout/', views.logout_view, name='logout'),
    path('user/update/', views.user_update, name='user_update'),
]








# # type:ignore
# from django.urls import path

# from contact import views

# app_name = 'contact'

# urlpatterns = [
#     path('', views.index, name='index'),
#     path('search/', views.search, name='search'),

#     # contact (CRUD)
#     path('contact/<int:contact_id>/', views.contact, name='contact'),
#     path('contact/create/', views.create, name='create'),
#     path('contact/<int:contact_id>/update/', views.update, name='update'),
#     path('contact/<int:contact_id>/delete/', views.delete, name='delete'),

#     # user
#     path('user/create/', views.register, name='register'),
# ]








# # type:ignore
# from django.urls import path

# from contact import views

# app_name = 'contact'

# urlpatterns = [
#     path('', views.index, name='index'),
#     path('search/', views.search, name='search'),

#     # contact (CRUD)
#     path('contact/<int:contact_id>/', views.contact, name='contact'),
#     path('contact/create/', views.create, name='create'),
#     path('contact/<int:contact_id>/update/', views.update, name='update'),
#     path('contact/<int:contact_id>/delete/', views.delete, name='delete'),
# ]








# # type:ignore
# from django.urls import path

# from contact import views

# app_name = 'contact'

# urlpatterns = [
#     path('', views.index, name='index'),
#     path('search/', views.search, name='search'),

#     # contact (CRUD)
#     path('contact/<int:contact_id>/', views.contact, name='contact'),
#     path('contact/create/', views.create, name='create'),
#     path('contact/<int:contact_id>/update/', views.update, name='update'),
# ]








# # type:ignore
# from django.urls import path

# from contact import views

# app_name = 'contact'

# urlpatterns = [
#     path('', views.index, name='index'),
#     path('search/', views.search, name='search'),

#     # contact (CRUD)
#     path('contact/<int:contact_id>/', views.contact, name='contact'),
#     path('contact/create/', views.create, name='create'),
# ]








# from django.urls import path

# from contact import views

# app_name = 'contact'

# urlpatterns = [
#     path('<int:contact_id>/', views.contact, name='contact'),  # type:ignore
#     path('search/', views.search, name='search'),  # type:ignore
#     path('', views.index, name='index'),  # type:ignore
# ]








# from django.urls import path

# from contact import views

# app_name = 'contact'

# urlpatterns = [
#     path('<int:contact_id>/', views.contact, name='contact'),  # type:ignore
#     path('', views.index, name='index'),  # type:ignore
# ]





# from django.urls import path

# from contact import views

# app_name = 'contact'

# urlpatterns = [
#     path('', views.index, name='index'),
# ]

project/urls.py
# from django.contrib import admin
# from django.urls import path

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]


# from django.contrib import admin
# from django.urls import include, path

# urlpatterns = [
#     path('', include('contact.urls')),
#     path('admin/', admin.site.urls),
# ]


from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/models.py
# from django.db import models

# # Create your models here.





# from django.db import models
# from django.utils import timezone

# # id (primary key - automático)
# # first_name (string), last_name (string), phone (string)
# # email (email), created_date (date), description (text)

# # Depois
# # category (foreign key), show (boolean), owner (foreign key)
# # picture (imagem)


# class Contact(models.Model):
#     first_name = models.CharField(max_length=50)
#     last_name = models.CharField(max_length=50, blank=True)
#     phone = models.CharField(max_length=50)
#     email = models.EmailField(max_length=254, blank=True)
#     created_date = models.DateTimeField(default=timezone.now)
#     description = models.TextField(blank=True)
#     show = models.BooleanField(default=True)
#     picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m/')

#     def __str__(self) -> str:
#         return f'{self.first_name} {self.last_name}'



from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

# id (primary key - automático)
# first_name (string), last_name (string), phone (string)
# email (email), created_date (date), description (text)
# category (foreign key), show (boolean), picture (imagem)

# Depois
# owner (foreign key)




class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name


class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50)
    email = models.EmailField(max_length=254, blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/')
    # picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m/')
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        blank=True, null=True
    )
    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True, null=True
    )    

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

contact/views/contact_forms.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from contact.forms import ContactForm
from contact.models import Contact


@login_required(login_url='contact:login')
def create(request):
    form_action = reverse('contact:create')

    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES)

        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():
            contact = form.save(commit=False)
            contact.owner = request.user
            contact.save()
            return redirect('contact:update', contact_id=contact.pk)

        return render(
            request,
            'contact/create.html',
            context
        )

    context = {
        'form': ContactForm(),
        'form_action': form_action,
    }

    return render(
        request,
        'contact/create.html',
        context
    )


@login_required(login_url='contact:login')
def update(request, contact_id):
    contact = get_object_or_404(
        Contact, pk=contact_id, show=True
    )

    # Verifica se o usuário é o dono do contato ou se é um administrador
    # ou superusuário
    if contact.owner != request.user and not request.user.is_staff \
            and not request.user.is_superuser:
        return redirect('contact:index')  # Ou exiba uma mensagem de erro

    form_action = reverse('contact:update', args=(contact_id,))

    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES, instance=contact)

        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():
            contact = form.save()
            return redirect('contact:update', contact_id=contact.pk)

        return render(
            request,
            'contact/create.html',
            context
        )

    context = {
        'form': ContactForm(instance=contact),
        'form_action': form_action,
    }

    return render(
        request,
        'contact/create.html',
        context
    )


@login_required(login_url='contact:login')
def delete(request, contact_id):
    contact = get_object_or_404(
        Contact, pk=contact_id, show=True
    )
    # Verifica se o usuário é o dono do contato ou se é um administrador
    # ou superusuário
    if contact.owner != request.user and not request.user.is_staff \
            and not request.user.is_superuser:
        return redirect('contact:index')  # Ou exiba uma mensagem de erro

    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        contact.delete()
        return redirect('contact:index')

    return render(
        request,
        'contact/contact.html',
        {
            'contact': contact,
            'confirmation': confirmation,
        }
    )








# from django.shortcuts import get_object_or_404, redirect, render
# from django.urls import reverse

# from contact.forms import ContactForm
# from contact.models import Contact


# def create(request):
#     form_action = reverse('contact:create')

#     if request.method == 'POST':
#         form = ContactForm(request.POST, request.FILES)

#         context = {
#             'form': form,
#             'form_action': form_action,
#         }

#         if form.is_valid():
#             contact = form.save()
#             return redirect('contact:update', contact_id=contact.pk)

#         return render(
#             request,
#             'contact/create.html',
#             context
#         )

#     context = {
#         'form': ContactForm(),
#         'form_action': form_action,
#     }

#     return render(
#         request,
#         'contact/create.html',
#         context
#     )


# def update(request, contact_id):
#     contact = get_object_or_404(
#         Contact, pk=contact_id, show=True
#     )
#     form_action = reverse('contact:update', args=(contact_id,))

#     if request.method == 'POST':
#         form = ContactForm(request.POST, request.FILES, instance=contact)

#         context = {
#             'form': form,
#             'form_action': form_action,
#         }

#         if form.is_valid():
#             contact = form.save()
#             return redirect('contact:update', contact_id=contact.pk)

#         return render(
#             request,
#             'contact/create.html',
#             context
#         )

#     context = {
#         'form': ContactForm(instance=contact),
#         'form_action': form_action,
#     }

#     return render(
#         request,
#         'contact/create.html',
#         context
#     )


# def delete(request, contact_id):
#     contact = get_object_or_404(
#         Contact, pk=contact_id, show=True
#     )
#     confirmation = request.POST.get('confirmation', 'no')

#     if confirmation == 'yes':
#         contact.delete()
#         return redirect('contact:index')

#     return render(
#         request,
#         'contact/contact.html',
#         {
#             'contact': contact,
#             'confirmation': confirmation,
#         }
#     )








# from django.shortcuts import get_object_or_404, redirect, render
# from django.urls import reverse

# from contact.forms import ContactForm
# from contact.models import Contact


# def create(request):
#     form_action = reverse('contact:create')

#     if request.method == 'POST':
#         form = ContactForm(request.POST)

#         context = {
#             'form': form,
#             'form_action': form_action,
#         }

#         if form.is_valid():
#             contact = form.save()
#             return redirect('contact:update', contact_id=contact.pk)

#         return render(
#             request,
#             'contact/create.html',
#             context
#         )

#     context = {
#         'form': ContactForm(),
#         'form_action': form_action,
#     }

#     return render(
#         request,
#         'contact/create.html',
#         context
#     )


# def update(request, contact_id):
#     contact = get_object_or_404(
#         Contact, pk=contact_id, show=True
#     )
#     form_action = reverse('contact:update', args=(contact_id,))

#     if request.method == 'POST':
#         form = ContactForm(request.POST, instance=contact)

#         context = {
#             'form': form,
#             'form_action': form_action,
#         }

#         if form.is_valid():
#             contact = form.save()
#             return redirect('contact:update', contact_id=contact.pk)

#         return render(
#             request,
#             'contact/create.html',
#             context
#         )

#     context = {
#         'form': ContactForm(instance=contact),
#         'form_action': form_action,
#     }

#     return render(
#         request,
#         'contact/create.html',
#         context
#     )


# def delete(request, contact_id):
#     contact = get_object_or_404(
#         Contact, pk=contact_id, show=True
#     )
#     confirmation = request.POST.get('confirmation', 'no')

#     if confirmation == 'yes':
#         contact.delete()
#         return redirect('contact:index')

#     return render(
#         request,
#         'contact/contact.html',
#         {
#             'contact': contact,
#             'confirmation': confirmation,
#         }
#     )








# from django.shortcuts import get_object_or_404, redirect, render
# from django.urls import reverse

# from contact.forms import ContactForm
# from contact.models import Contact


# def create(request):
#     form_action = reverse('contact:create')

#     if request.method == 'POST':
#         form = ContactForm(request.POST)

#         context = {
#             'form': form,
#             'form_action': form_action,
#         }

#         if form.is_valid():
#             contact = form.save()
#             return redirect('contact:update', contact_id=contact.pk)

#         return render(
#             request,
#             'contact/create.html',
#             context
#         )

#     context = {
#         'form': ContactForm(),
#         'form_action': form_action,
#     }

#     return render(
#         request,
#         'contact/create.html',
#         context
#     )


# def update(request, contact_id):
#     contact = get_object_or_404(
#         Contact, pk=contact_id, show=True
#     )
#     form_action = reverse('contact:update', args=(contact_id,))

#     if request.method == 'POST':
#         form = ContactForm(request.POST, instance=contact)

#         context = {
#             'form': form,
#             'form_action': form_action,
#         }

#         if form.is_valid():
#             contact = form.save()
#             return redirect('contact:update', contact_id=contact.pk)

#         return render(
#             request,
#             'contact/create.html',
#             context
#         )

#     context = {
#         'form': ContactForm(instance=contact),
#         'form_action': form_action,
#     }

#     return render(
#         request,
#         'contact/create.html',
#         context
#     )








# from django.shortcuts import render

# from contact.forms import ContactForm


# def create(request):
#     if request.method == 'POST':
#         context = {
#             'form': ContactForm(request.POST)
#         }

#         return render(
#             request,
#             'contact/create.html',
#             context
#         )

#     context = {
#         'form': ContactForm()
#     }

#     return render(
#         request,
#         'contact/create.html',
#         context
#     )








# from typing import Any, Dict

# from django import forms
# from django.core.exceptions import ValidationError
# from django.core.paginator import Paginator
# from django.db.models import Q
# from django.shortcuts import get_object_or_404, redirect, render

contact/templates/contact/contact.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="single-contact">
    <h1 class="single-contact-name">
      {{ contact.first_name }} {{ contact.last_name }}
    </h1>

    <p><b>ID:</b> {{ contact.id }}</p>
    <p><b>E-mail:</b> {{ contact.email }}</p>
    <p><b>Phone:</b> {{ contact.phone }}</p>
    <p><b>Created Date:</b> {{ contact.created_date }}</p>
    <p><b>Description:</b> {{ contact.description }}</p>
    <p><b>Category:</b> {{ contact.category.name }}</p>

    {% if contact.picture %}
      <p>
        <img src="{{ contact.picture.url }}" alt="{{ contact.first_name }} {{ contact.last_name }}">
      </p>
    {% endif %}

    {% if user == contact.owner or user.is_staff or user.is_superuser %}
      <div class="contact-links">
        <a class="btn btn-link" href="{% url 'contact:update' contact.id %}">Update</a>

        <form action="{% url 'contact:delete' contact.id %}" method="POST">
          {% csrf_token %}

          {% if confirmation == 'no' %}
            <input type="hidden" name="confirmation" value="yes">
            <button class="btn btn-link btn-delete" type="submit">Confirma?</button>
          {% else %}
            <button class="btn btn-link btn-delete" type="submit">Delete</button>
          {% endif %}
        </form>
      </div>
    </div>
  {% endif %}
{% endblock content %}








{% comment %} {% extends 'global/base.html' %}

{% block content %}
  <div class="single-contact">
    <h1 class="single-contact-name">
      {{ contact.first_name }} {{ contact.last_name }}
    </h1>

    <p><b>ID:</b> {{ contact.id }}</p>
    <p><b>E-mail:</b> {{ contact.email }}</p>
    <p><b>Phone:</b> {{ contact.phone }}</p>
    <p><b>Created Date:</b> {{ contact.created_date }}</p>
    <p><b>Description:</b> {{ contact.description }}</p>
    <p><b>Category:</b> {{ contact.category.name }}</p>

    <div class="contact-links">
      <a class="btn btn-link" href="{% url 'contact:update' contact.id %}">Update</a>

      <form class="ms-2 d-inline" action="{% url 'contact:delete' contact.id %}" method="POST">
        {% csrf_token %}

        {% if confirmation == 'no' %}
          <input type="hidden" name="confirmation" value="yes">
          <button class="btn btn-link btn-delete" type="submit">Confirma?</button>
        {% else %}
          <button class="btn btn-link btn-delete" type="submit">Delete</button>
        {% endif %}
      </form>
    </div>
  </div>
{% endblock content %} {% endcomment %}








{% comment %} {% extends 'global/base.html' %}

{% block content %}
  <div class="single-contact">
    <h1 class="single-contact-name">
      {{ contact.first_name }} {{ contact.last_name }}
    </h1>

    <p><b>ID:</b> {{ contact.id }}</p>
    <p><b>E-mail:</b> {{ contact.email }}</p>
    <p><b>Phone:</b> {{ contact.phone }}</p>
    <p><b>Created Date:</b> {{ contact.created_date }}</p>
    <p><b>Description:</b> {{ contact.description }}</p>
    <p><b>Category:</b> {{ contact.category.name }}</p>
  </div>
{% endblock content %} {% endcomment %}

contact/templates/contact/create.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">

    <h2>Contact</h2>
    
    <form 
      action="{{ form_action }}"
      method="POST"
      enctype="multipart/form-data"
    >
      {% csrf_token %}      
      
      <div class="form-content">

        {% for field in form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {{ field.errors }}

            {% if field.help_text %}
              <p class="help-text">{{ field.help_text }}</p>
            {% endif %}
          </div>

          {% if field.name == 'picture' and field.value %}
            {% if field.value.url %}
              <div class="form-group">
                <img src="{{ field.value.url }}" alt="">
              </div>
            {% endif %}
          {% endif %}
        {% endfor %}
      </div>

      {% if form.non_field_errors %}
        <div class="form-content">
          <div class="form-group">
            <div class="message error">
              {{ form.non_field_errors }}
            </div>
          </div>
        </div>
      {% endif %}

      <div class="form-content">
        <div class="form-group">
          <button class="btn" type="submit">Send</button>
        </div>
      </div>

    </form>
  </div>
{% endblock content %}








{% comment %} {% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">

    <h2>Contact</h2>
    
    <form 
      action="{{ form_action }}"
      method="POST"
      enctype="multipart/form-data"
    >
      {% csrf_token %}      
      
      <div class="form-content">

        {% for field in form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {{ field.errors }}

            {% if field.help_text %}
              <p class="help-text">{{ field.help_text }}</p>
            {% endif %}
          </div>
        {% endfor %}
      </div>

      {% if form.non_field_errors %}
        <div class="form-content">
          <div class="form-group">
            <div class="message error">
              {{ form.non_field_errors }}
            </div>
          </div>
        </div>
      {% endif %}

      <div class="form-content">
        <div class="form-group">
          <button class="btn" type="submit">Send</button>
        </div>
      </div>

    </form>
  </div>
{% endblock content %} {% endcomment %}








{% comment %} {% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">

    <h2>Contact</h2>
    
    <form 
      action="{% url 'contact:create' %}"
      method="POST"
      enctype="multipart/form-data"
    >
      {% csrf_token %}      
      
      <div class="form-content">

        {% for field in form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {{ field.errors }}

            {% if field.help_text %}
              <p class="help-text">{{ field.help_text }}</p>
            {% endif %}
          </div>
        {% endfor %}
      </div>

      {% if form.non_field_errors %}
        <div class="form-content">
          <div class="form-group">
            <div class="message error">
              {{ form.non_field_errors }}
            </div>
          </div>
        </div>
      {% endif %}

      <div class="form-content">
        <div class="form-group">
          <button class="btn" type="submit">Send</button>
        </div>
      </div>

    </form>
  </div>
{% endblock content %} {% endcomment %}








{% comment %} {% extends 'global/base.html' %}
{% block content %}
  <div class="form-wrapper">

    <h2>Contact</h2>
    
    <form 
      action="{% url 'contact:create' %}"
      method="POST"
      enctype="multipart/form-data"
    >
      {% csrf_token %}      
      
      <div class="form-content">

        {% for field in form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {{ field.errors }}
          </div>
        {% endfor %}
      </div>

      {% if form.non_field_errors %}
        <div class="form-content">
          <div class="form-group">
            <div class="message error">
              {{ form.non_field_errors }}
            </div>
          </div>
        </div>
      {% endif %}

      <div class="form-content">
        <div class="form-group">
          <button class="btn" type="submit">Send</button>
        </div>
      </div>

    </form>
  </div>
{% endblock content %} {% endcomment %}








{% comment %} {% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">

    <h2>Contact</h2>
    
    <form 
      action="{% url 'contact:create' %}"
      method="POST"
      enctype="multipart/form-data"
    >
      {% csrf_token %}

      <div class="form-content">
        <div class="form-group">
          <label for="id_first_name">first_name</label>
          <input type="text" name="first_name" maxlength="255" id="id_first_name">
        </div>
        
        <div class="form-group">
          <label for="id_last_name">last_name</label>
          <input type="text" name="last_name" maxlength="255" id="id_last_name">
        </div>
      </div>

      <div class="form-content">
        <div class="form-group">
          <button class="btn" type="submit">Send</button>
        </div>
      </div>

    </form>
  </div>
{% endblock content %} {% endcomment %}








{% comment %} {% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">

    <h2>Contact</h2>
    
    <form 
      action=""
      method="POST"
      enctype="multipart/form-data"
    >
     {% csrf_token %}

    <div class="form-content">
      <div class="form-group">
        <label for="id_first_name">LABEL</label>
        <input type="text" name="first_name" maxlength="255" id="id_first_name">
      </div>
    </div>

    <div class="form-content">
      <div class="form-group">
        <button class="btn" type="submit">Send</button>
      </div>
    </div>

   </form>
  </div>
{% endblock content %} {% endcomment %}








{% comment %} {% extends 'global/base.html' %}

{% block content %}
  <h1>CREATE CONTACT</h1>
{% endblock content %} {% endcomment %}

contact/templates/contact/index.html
{% extends 'global/base.html' %}

{% block content %}
  {% if page_obj %}
    <div class="responsive-table">
      <table class="contacts-table">
        <caption class="table-caption ">
          Contacts
        </caption>

        <thead>
          <tr class="table-row table-row-header">
            <th class="table-header">ID</th>
            <th class="table-header">First Name</th>
            <th class="table-header">Last Name</th>
            <th class="table-header">Phone</th>
            <th class="table-header">E-mail</th>
          </tr>
        </thead>

        <tbody>
          {% for contact in page_obj %}
            <tr class="table-row">
              <td class="table-cel">
                <a 
                  class="table-link" 
                  href="{% url 'contact:contact' contact.id %}"
                >
                  {{ contact.id }}
                </a>
              </td>
              <td class="table-cel">
                {{ contact.first_name }}
              </td>
              <td class="table-cel">
                {{ contact.last_name }}
              </td>
              <td class="table-cel">
                {{ contact.phone }}
              </td>
              <td class="table-cel">
                {{ contact.email }}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  {% else %}
    <div class="single-contact">
      <h1 class="single-contact-name">
        Nenhum contato encontrado.
      </h1>
    </div>
  {% endif %}
{% endblock content %}








{% comment %} {% extends 'global/base.html' %}

{% block content %}
  <div class="responsive-table">
    <table class="contacts-table">
      <caption class="table-caption ">
        Contacts
      </caption>

      <thead>
        <tr class="table-row table-row-header">
          <th class="table-header">ID</th>
          <th class="table-header">First Name</th>
          <th class="table-header">Last Name</th>
          <th class="table-header">Phone</th>
          <th class="table-header">E-mail</th>
        </tr>
      </thead>

      <tbody>
        {% for contact in contacts %}
          <tr class="table-row">
            <td class="table-cel">
              <a 
                class="table-link" 
                href="{% url 'contact:contact' contact.id %}"
              >                
                {{ contact.id }}
              </a>
            </td>
            <td class="table-cel">
              {{ contact.first_name }}
            </td>
            <td class="table-cel">
              {{ contact.last_name }}
            </td>
            <td class="table-cel">
              {{ contact.phone }}
            </td>
            <td class="table-cel">
              {{ contact.email }}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock content %} {% endcomment %}














{% comment %} {% extends 'global/base.html' %}

{% block content %}
  {% for contact in contacts %}
    {{ contact.first_name }} <br>
  {% endfor %}
{% endblock content %} {% endcomment %}

contact/templates/contact/login.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">

    <h2>Login </h2>
    
    {% if user.is_authenticated %}
      <p>
        Você fez login como {{ user.username }}.
        Clique <a href="{% url 'contact:logout' %}">aqui</a>
        para sair.
      </p>
    {% else %}
      {% include 'contact/partials/_user-form.html' %}
    {% endif %}
  </div>
{% endblock content %}

contact/templates/contact/register.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">

    <h2>Register</h2>
    
    {% include 'contact/partials/_user-form.html' %}
  </div>
{% endblock content %}








{% comment %} {% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">

    <h2>Register</h2>
    
    <form 
      action="{{ form_action }}"
      method="POST"
    >
      {% csrf_token %}      
      
      <div class="form-content">

        {% for field in form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {{ field.errors }}

            {% if field.help_text %}
              <p class="help-text">{{ field.help_text }}</p>
            {% endif %}
          </div>
        {% endfor %}
      </div>

      {% if form.non_field_errors %}
        <div class="form-content">
          <div class="form-group">
            <div class="message error">
              {{ form.non_field_errors }}
            </div>
          </div>
        </div>
      {% endif %}

      <div class="form-content">
        <div class="form-group">
          <button class="btn" type="submit">Send</button>
        </div>
      </div>

    </form>
  </div>
{% endblock content %} {% endcomment %}

contact/templates/contact/user_update.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">

    <h2>Update User</h2>
    
    {% include 'contact/partials/_user-form.html' %}
  </div>
{% endblock content %}